{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultlens.fullname" . }}
  labels:
    {{- include "vaultlens.labels" . | nindent 4 }}
type: Opaque
data:
  vault-system-token: {{ .Values.systemToken | default "" | b64enc | quote }}
{{- end }}
