apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultlens.fullname" . }}
  labels:
    {{- include "vaultlens.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if eq (.Values.config.audit.source | default "socket") "socket" }}
    - port: {{ .Values.config.socketAudit.port | default 9090 | int }}
      targetPort: audit-socket
      protocol: TCP
      name: audit-socket
    {{- end }}
  selector:
    {{- include "vaultlens.selectorLabels" . | nindent 4 }}
